# Generated by Django 3.2.8 on 2022-02-24 09:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=50)),
                ('cluster_name', models.CharField(max_length=50)),
                ('url1', models.CharField(max_length=255)),
                ('url2', models.CharField(max_length=255)),
                ('url3', models.CharField(max_length=255)),
                ('depth', models.IntegerField(default=None)),
                ('pdf', models.BooleanField(default=None)),
                ('word', models.BooleanField(default=None)),
                ('powerpoint', models.BooleanField(default=None)),
                ('text', models.BooleanField(default=None)),
                ('non_html_text', models.BooleanField(default=None)),
                ('date_of_creation', models.DateField(default=datetime.date(2022, 2, 24))),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrawledData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=255)),
                ('date_of_creation', models.DateField(default=datetime.date(2022, 2, 24))),
                ('root_url', models.CharField(default=None, max_length=255)),
                ('current_url', models.CharField(default=None, max_length=255)),
                ('crawled_data_type', models.CharField(default=None, max_length=25)),
                ('content', models.CharField(default=None, max_length=100000)),
                ('depth', models.IntegerField(default=None)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
