# Generated by Django 3.2.9 on 2022-04-09 20:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2022, 4, 10)),
        ),
        migrations.AlterField(
            model_name='crawleddata',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2022, 4, 10)),
        ),
        migrations.CreateModel(
            name='Scrappers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=255)),
                ('file_type', models.CharField(default=None, max_length=255)),
                ('enable', models.BooleanField(default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
